# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_person_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
